-- Create sequences
CREATE SEQUENCE E_ID INCREMENT BY 1 START WITH 1001 MAXVALUE 1008;
CREATE SEQUENCE AU_ID INCREMENT BY 1 START WITH 456 MAXVALUE 460;
CREATE SEQUENCE ARTIST_ID INCREMENT BY 1 START WITH 5001 MAXVALUE 5005;
CREATE SEQUENCE SELL_ID INCREMENT BY 1 START WITH 41 MAXVALUE 46;

-- Create MANAGER table
CREATE TABLE MANAGER(
  M_ID NUMBER(10) NOT NULL,
  M_NAME VARCHAR2(50),
  M_PHONE NUMBER(10),
  MADDRESS VARCHAR2(50),
  CONSTRAINT M_PK1 PRIMARY KEY (M_ID)
);

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE(
  E_ID NUMBER(10) NOT NULL,
  E_NAME VARCHAR2(50),
  E_ADDRESS VARCHAR2(50),
  JOB_TYPE VARCHAR2(50),
  CONSTRAINT E_PK PRIMARY KEY (E_ID)
);

-- Create OWNER table
CREATE TABLE OWNER (
  O_ID NUMBER(10),
  O_NAME VARCHAR2(50),
  O_ADDRESS VARCHAR2(50),
  CITY VARCHAR2(30),
  COUNTRY VARCHAR2(30),
  PRIMARY KEY (O_ID)
);

-- Create ART_GALLERY table
CREATE TABLE ART_GALLERY(
  A_ID NUMBER(10) NOT NULL,
  A_NAME VARCHAR2(50),
  LOCATION VARCHAR2(30),
  CONSTRAINT A_ID_PK PRIMARY KEY (A_ID)
);

-- Create EXHIBITION table
CREATE TABLE EXHIBITION(
  ROOM_NO NUMBER(10),
  WATCH_TIME VARCHAR2(20),
  TYPE VARCHAR2(20),
  PRIMARY KEY (ROOM_NO)
);

-- Create AUCTION table
CREATE TABLE AUCTION(
  AUCTION_ID NUMBER(10),
  DATE_OF DATE,
  TIME_SHIFT VARCHAR2(20),
  PRIMARY KEY (AUCTION_ID)
);

-- Create AUCTIONER table
CREATE TABLE AUCTIONER(
  AU_ID NUMBER(10) NOT NULL,
  AU_NAME VARCHAR2(50),
  AU_EMAIL VARCHAR2(50),
  PRIMARY KEY (AU_ID)
);

-- Create ART table
CREATE TABLE ART(
  ART_NO NUMBER(10),
  ART_PRICE NUMBER(20),
  GENRE VARCHAR2(50),
  CATAGORY VARCHAR2(50),
  PRIMARY KEY (ART_NO)
);

-- Create ARTIST table
CREATE TABLE ARTIST(
  ARTIST_ID NUMBER(10),
  NO_OF_PAINTING NUMBER(20),
  ARTIST_NAME VARCHAR2(50),
  PRIMARY KEY (ARTIST_ID)
);

-- Create VISITORS table
CREATE TABLE VISITORS(
  PASS_ID NUMBER(10),
  V_NAME VARCHAR2(50),
  V_PHONE NUMBER(10),
  PRIMARY KEY (PASS_ID)
);

-- Create GUIDES table
CREATE TABLE GUIDES(
  G_ID NUMBER(10),
  G_NAME VARCHAR2(50),
  SECTION VARCHAR2(50),
  G_EMAIL VARCHAR2(50),
  PRIMARY KEY (G_ID)
);

-- Create TICKET table
CREATE TABLE TICKET(
  T_ID NUMBER(10),
  DATE_OF DATE,
  PRICE NUMBER(20),
  PRIMARY KEY (T_ID)
);

-- Create SELLER table
CREATE TABLE SELLER(
  SELL_ID NUMBER(10),
  SELL_NAME VARCHAR2(50),
  SELL_PHONE NUMBER(10),
  PRIMARY KEY (SELL_ID)
);