-- Insert into MANAGER
INSERT INTO MANAGER(M_ID, M_NAME, M_PHONE, MADDRESS) VALUES (101, 'ABUL', 0175343911, 'DHAKA');
INSERT INTO MANAGER(M_ID, M_NAME, M_PHONE, MADDRESS) VALUES (102, 'BABUL', 0179434734, 'MIRPUR');
INSERT INTO MANAGER(M_ID, M_NAME, M_PHONE, MADDRESS) VALUES (103, 'KHALEK', 0173211231, 'KURIL');
INSERT INTO MANAGER(M_ID, M_NAME, M_PHONE, MADDRESS) VALUES (104, 'MALEK', 017534329, 'UTTARA');
INSERT INTO MANAGER(M_ID, M_NAME, M_PHONE, MADDRESS) VALUES (105, 'JABBAR', 0174566543, 'KAWLA');

-- Insert into EMPLOYEE
INSERT INTO EMPLOYEE(E_ID, E_NAME, E_ADDRESS, JOB_TYPE) VALUES (E_ID.NEXTVAL, 'FAHIM', 'GULSHAN', 'OFFICER');
INSERT INTO EMPLOYEE(E_ID, E_NAME, E_ADDRESS, JOB_TYPE) VALUES (E_ID.NEXTVAL, 'KARIM', 'BADDA', 'FRONT MANAGER');
INSERT INTO EMPLOYEE(E_ID, E_NAME, E_ADDRESS, JOB_TYPE) VALUES (E_ID.NEXTVAL, 'SAFIQ', 'GULISTAN', 'CLERK');
INSERT INTO EMPLOYEE(E_ID, E_NAME, E_ADDRESS, JOB_TYPE) VALUES (E_ID.NEXTVAL, 'RAFIQ', 'RAMPURA', 'RECEPTION');
INSERT INTO EMPLOYEE(E_ID, E_NAME, E_ADDRESS, JOB_TYPE) VALUES (E_ID.NEXTVAL, 'JABBAR', 'BANANI', 'CLEANER');

-- Insert into OWNER
INSERT INTO OWNER(O_ID, O_NAME, O_ADDRESS, CITY, COUNTRY) VALUES (22464021, 'AL FAHIM', 'KAMLAPUR', 'DHAKA', 'BANGLADESH');

-- Insert into ART_GALLERY
INSERT INTO ART_GALLERY(A_ID, A_NAME, LOCATION) VALUES (01, 'LEONARD DA VINCI', 'COLUME 1');
INSERT INTO ART_GALLERY(A_ID, A_NAME, LOCATION) VALUES (02, 'JAYNUL ABEDIN', 'COLUME 2');
INSERT INTO ART_GALLERY(A_ID, A_NAME, LOCATION) VALUES (03, 'KAMRUL HASAN', 'COLUME 3');
INSERT INTO ART_GALLERY(A_ID, A_NAME, LOCATION) VALUES (04, 'VINCENT VAN GOGH', 'COLUME 4');
INSERT INTO ART_GALLERY(A_ID, A_NAME, LOCATION) VALUES (05, 'S M SULTAN', 'COLUME 5');

-- Insert into EXHIBITION
INSERT INTO EXHIBITION(ROOM_NO, WATCH_TIME, TYPE) VALUES (222, '8.00-9.00', 'DIGITAL ART');
INSERT INTO EXHIBITION(ROOM_NO, WATCH_TIME, TYPE) VALUES (333, '9.00-10.00', 'COLOR PAINTING');
INSERT INTO EXHIBITION(ROOM_NO, WATCH_TIME, TYPE) VALUES (444, '10.00-11.00', 'NFT');
INSERT INTO EXHIBITION(ROOM_NO, WATCH_TIME, TYPE) VALUES (555, '11.00-12.00', 'PERFORM ART');
INSERT INTO EXHIBITION(ROOM_NO, WATCH_TIME, TYPE) VALUES (666, '12.00-1.00', 'SCULPTURE');

-- Insert into AUCTION
INSERT INTO AUCTION(AUCTION_ID, DATE_OF, TIME_SHIFT) VALUES (1122, TO_DATE('11-JAN-23', 'DD-MON-RR'), '8.00-9.00');
INSERT INTO AUCTION(AUCTION_ID, DATE_OF, TIME_SHIFT) VALUES (1133, TO_DATE('12-JAN-23', 'DD-MON-RR'), '9.00-10.00');
INSERT INTO AUCTION(AUCTION_ID, DATE_OF, TIME_SHIFT) VALUES (1144, TO_DATE('13-JAN-23', 'DD-MON-RR'), '8.00-9.00');
INSERT INTO AUCTION(AUCTION_ID, DATE_OF, TIME_SHIFT) VALUES (1155, TO_DATE('14-JAN-23', 'DD-MON-RR'), '8.00-9.00');
INSERT INTO AUCTION(AUCTION_ID, DATE_OF, TIME_SHIFT) VALUES (1166, TO_DATE('14-JAN-23', 'DD-MON-RR'), '8.00-9.00');

-- Insert into AUCTIONER
INSERT INTO AUCTIONER(AU_ID, AU_NAME, AU_EMAIL) VALUES (AU_ID.NEXTVAL, 'OSMAN', 'OSMAN@GMAIL.COM');
INSERT INTO AUCTIONER(AU_ID, AU_NAME, AU_EMAIL) VALUES (AU_ID.NEXTVAL, 'TITAS', 'TITAS@GMAIL.COM');
INSERT INTO AUCTIONER(AU_ID, AU_NAME, AU_EMAIL) VALUES (AU_ID.NEXTVAL, 'SAIKAT', 'SAIKAT@GMAIL.COM');
INSERT INTO AUCTIONER(AU_ID, AU_NAME, AU_EMAIL) VALUES (AU_ID.NEXTVAL, 'RUSELL', 'RUSELL@GMAIL.COM');
INSERT INTO AUCTIONER(AU_ID, AU_NAME, AU_EMAIL) VALUES (AU_ID.NEXTVAL, 'SAIMON', 'SAIMON@GMAIL.COM');

-- Insert into ART
INSERT INTO ART(ART_NO, ART_PRICE, GENRE, CATAGORY) VALUES (4001, 1000, 'PAINTING', 'ELITE');
INSERT INTO ART(ART_NO, ART_PRICE, GENRE, CATAGORY) VALUES (4002, 2000, 'LITERATURE', 'CLASSIC');
INSERT INTO ART(ART_NO, ART_PRICE, GENRE, CATAGORY) VALUES (4003, 3000, 'ARCHITECTURE', 'GENERAL');
INSERT INTO ART(ART_NO, ART_PRICE, GENRE, CATAGORY) VALUES (4004, 4000, 'FINE ART', 'ALPHA');
INSERT INTO ART(ART_NO, ART_PRICE, GENRE, CATAGORY) VALUES (4005, 5000, 'VISUAL ART', 'BRAVO');

-- Insert into ARTIST
INSERT INTO ARTIST(ARTIST_ID, NO_OF_PAINTING, ARTIST_NAME) VALUES (ARTIST_ID.NEXTVAL, 10, 'JAYNUL ABEDIN');
INSERT INTO ARTIST(ARTIST_ID, NO_OF_PAINTING, ARTIST_NAME) VALUES (ARTIST_ID.NEXTVAL, 20, 'KAMRUL HASAN');
INSERT INTO ARTIST(ARTIST_ID, NO_OF_PAINTING, ARTIST_NAME) VALUES (ARTIST_ID.NEXTVAL, 3, 'RIFAT');
INSERT INTO ARTIST(ARTIST_ID, NO_OF_PAINTING, ARTIST_NAME) VALUES (ARTIST_ID.NEXTVAL, 10, 'WYANG CHO PA');
INSERT INTO ARTIST(ARTIST_ID, NO_OF_PAINTING, ARTIST_NAME) VALUES (ARTIST_ID.NEXTVAL, 8, 'MICHEELE ANGELO');

-- Insert into VISITORS
INSERT INTO VISITORS(PASS_ID, V_NAME, V_PHONE) VALUES (4223, 'JABBAR', 999922);
INSERT INTO VISITORS(PASS_ID, V_NAME, V_PHONE) VALUES (4224, 'KUDDUS', 123401);
INSERT INTO VISITORS(PASS_ID, V_NAME, V_PHONE) VALUES (4225, 'BARKAT', 567802);
INSERT INTO VISITORS(PASS_ID, V_NAME, V_PHONE) VALUES (4226, 'AUWAL', 876504);
INSERT INTO VISITORS(PASS_ID, V_NAME, V_PHONE) VALUES (4227, 'RUHUL', 442204);

-- Insert into GUIDES
INSERT INTO GUIDES(G_ID, G_NAME, SECTION, G_EMAIL) VALUES (007, 'JAMES BOND', 'MI6', 'JAMESBOND@GMAIL.COM');
INSERT INTO GUIDES(G_ID, G_NAME, SECTION, G_EMAIL) VALUES (008, 'ETHAN HUNT', 'MI', 'ETHANHUNT@GMAIL.COM');
INSERT INTO GUIDES(G_ID, G_NAME, SECTION, G_EMAIL) VALUES (009, 'MASUD RANA', 'NSI', 'MASUDRANA@GMAIL.COM');
INSERT INTO GUIDES(G_ID, G_NAME, SECTION, G_EMAIL) VALUES (23, 'SHERLOCK HOLMES', 'BAKER STREET', 'SHERLOCKHOLMES@GMAIL.COM');
INSERT INTO GUIDES(G_ID, G_NAME, SECTION, G_EMAIL) VALUES (010, 'LIONEL MESSI', 'ARG', 'LIONELMESSI@GMAIL.COM');

-- Insert into TICKET
INSERT INTO TICKET(T_ID, DATE_OF, PRICE) VALUES (99, TO_DATE('11-JAN-23', 'DD-MON-RR'), 50);
INSERT INTO TICKET(T_ID, DATE_OF, PRICE) VALUES (199, TO_DATE('11-JAN-23', 'DD-MON-RR'), 50);
INSERT INTO TICKET(T_ID, DATE_OF, PRICE) VALUES (299, TO_DATE('11-JAN-23', 'DD-MON-RR'), 50);
INSERT INTO TICKET(T_ID, DATE_OF, PRICE) VALUES (399, TO_DATE('11-JAN-23', 'DD-MON-RR'), 50);
INSERT INTO TICKET(T_ID, DATE_OF, PRICE) VALUES (499, TO_DATE('11-JAN-23', 'DD-MON-RR'), 50);

-- Insert into SELLER
INSERT INTO SELLER(SELL_ID, SELL_NAME, SELL_PHONE) VALUES (SELL_ID.NEXTVAL, 'MONJU', 2942685);
INSERT INTO SELLER(SELL_ID, SELL_NAME, SELL_PHONE) VALUES (SELL_ID.NEXTVAL, 'RAHAT', 3912695);
INSERT INTO SELLER(SELL_ID, SELL_NAME, SELL_PHONE) VALUES (SELL_ID.NEXTVAL, 'SAKIB', 4975315);
INSERT INTO SELLER(SELL_ID, SELL_NAME, SELL_PHONE) VALUES (SELL_ID.NEXTVAL, 'RAHIM', 5995115);
INSERT INTO SELLER(SELL_ID, SELL_NAME, SELL_PHONE) VALUES (SELL_ID.NEXTVAL, 'NAHID', 6985264);